"""empty message

Revision ID: 238793345374
Revises: 52314d6a6dbc
Create Date: 2022-08-24 22:36:49.927227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238793345374'
down_revision = '52314d6a6dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MiHoYo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('cookie', sa.String(length=350), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cookie'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MiHoYo')
    # ### end Alembic commands ###
